name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and run Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up --build
      - name: Run frontend tests
        run: docker-compose exec -T frontend npm run test || true
        continue-on-error: true  
          
      - name: Run backend tests
        run: docker-compose exec -T backend npm run test
        continue-on-error: true

     
      - name: Copy Playwright report from container
        run: |
          docker cp $(docker-compose ps -q frontend):/app/playwright-report ./playwright-report

      - name: Upload Playwright report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: playwright-report
          retention-days: 7

      - name: Shutdown Docker Compose
        run: docker-compose down
